//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StarbucksMobileApp.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LanguageResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LanguageResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StarbucksMobileApp.Resources.Languages.LanguageResource", typeof(LanguageResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starbucks Türkiye.
        /// </summary>
        internal static string _Shared_App_Name {
            get {
                return ResourceManager.GetString("_Shared_App_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starbuck.
        /// </summary>
        internal static string _Shared_App_Title {
            get {
                return ResourceManager.GetString("_Shared_App_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İptal.
        /// </summary>
        internal static string _Shared_Btn_CANCEL {
            get {
                return ResourceManager.GetString("_Shared_Btn_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Onayla.
        /// </summary>
        internal static string _Shared_Btn_CONFIRM {
            get {
                return ResourceManager.GetString("_Shared_Btn_CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sil.
        /// </summary>
        internal static string _Shared_Btn_DELETE {
            get {
                return ResourceManager.GetString("_Shared_Btn_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çıkış Yap.
        /// </summary>
        internal static string _Shared_Btn_LOGOUT {
            get {
                return ResourceManager.GetString("_Shared_Btn_LOGOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hayır.
        /// </summary>
        internal static string _Shared_Btn_NO {
            get {
                return ResourceManager.GetString("_Shared_Btn_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tamam.
        /// </summary>
        internal static string _Shared_Btn_OK {
            get {
                return ResourceManager.GetString("_Shared_Btn_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaydet.
        /// </summary>
        internal static string _Shared_Btn_SAVE {
            get {
                return ResourceManager.GetString("_Shared_Btn_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evet.
        /// </summary>
        internal static string _Shared_Btn_YES {
            get {
                return ResourceManager.GetString("_Shared_Btn_YES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Belirtmek İstemiyorum.
        /// </summary>
        internal static string _Shared_CinsiyetBI {
            get {
                return ResourceManager.GetString("_Shared_CinsiyetBI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erkek.
        /// </summary>
        internal static string _Shared_CinsiyetErkek {
            get {
                return ResourceManager.GetString("_Shared_CinsiyetErkek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kadın.
        /// </summary>
        internal static string _Shared_CinsiyetKadin {
            get {
                return ResourceManager.GetString("_Shared_CinsiyetKadin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMS gönderme işlemi başarısız oldu, lütfen daha sonra tekrar deneyin!.
        /// </summary>
        internal static string _Shared_ErrorSMS {
            get {
                return ResourceManager.GetString("_Shared_ErrorSMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hata oluştu!.
        /// </summary>
        internal static string _Shared_ErrorText {
            get {
                return ResourceManager.GetString("_Shared_ErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen bekleyin.
        /// </summary>
        internal static string _Shared_Loading {
            get {
                return ResourceManager.GetString("_Shared_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bekar.
        /// </summary>
        internal static string _Shared_MedeniDurumBekar {
            get {
                return ResourceManager.GetString("_Shared_MedeniDurumBekar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Belirtmek İstemiyorum.
        /// </summary>
        internal static string _Shared_MedeniDurumBI {
            get {
                return ResourceManager.GetString("_Shared_MedeniDurumBI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evli.
        /// </summary>
        internal static string _Shared_MedeniDurumEvli {
            get {
                return ResourceManager.GetString("_Shared_MedeniDurumEvli", resourceCulture);
            }
        }
    }
}
